### ISSUE TITLE
aside-menu hidden on smaller screens

### ISSUE THREAD

**Issue by dacodekid** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#183]
The below code prevents `aside-menu` being shown while toggling.

https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/Static_Starter_GULP/scss/core/_layout.scss#L310-L312

**Comment by dacodekid** [comment]
In case if anyone else having this issue, this snippet fixes this issue

```css
// aside-menu not showing up on mobile size
// fix it by setting up margin-right to 0

@media (max-width: 991px) {
  .aside-menu-toggler {
    top: -10px !important;
  }

  .aside-menu {
    margin-right: 0;
  }
}
```

**Comment by dacodekid** [comment]
@mrholek would you please take a loot at this one?

**Comment by mrholek** [comment]
@dacodekid sure. I will check it and fix it.

**Comment by dacodekid** [comment]
@mrholek with current commit https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/commit/d104609bafafd68ab4a4856cac73e50f98ace2e9 now the `aside-menu toggler` shows in mobile view.  However

1. I'm unable to click the menu

2. `navbar nav-item` elements are little off of alignment (dropdown & the toggler)
![image](https://user-images.githubusercontent.com/10047844/29175241-7e2736fc-7db6-11e7-8ea2-3cfcf14b352b.png)

To fix, now I've to update the code from above, like this

```css
// aside-menu not showing up on mobile size
// fix it by setting up margin-right to 0
@media (max-width: 991px) {

  // sidebar items aligning a little off of vertical centering
  .app-header.navbar .nav-item {
    top: -10px !important;
  }

  // move the toggler even a little more
  .aside-menu-toggler {
    top: -10px !important;
  }

  // unable to click the menu without this code
  .aside-menu {
    margin-right: 0;
  }
}
```

This gets me 
![image](https://user-images.githubusercontent.com/10047844/29175606-790b788a-7db7-11e7-88d1-69e403f7fa01.png)
